# Enviorment 

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
from scipy import stats
import seaborn as sns
from  matplotlib import pyplot as plt
import networkx as nx
plt.style.use('ggplot')
from tqdm import tqdm_notebook
import swifter
import qgrid
import numpy as np
import networkx as nx
import random
from scipy.sparse import spdiags
from functools import partial
import mygene
import sys

# Loading heterogeneous network

loading heterogeneous network(STRING physical ensembl gene ID node 18358, KEGG pathway node 271, total 18631)

In [9]:
G = nx.read_edgelist("../data/heterogeneous_STRINGPhysical_gene_KEGG.txt")

In [10]:
print(nx.info(G))

Name: 
Type: Graph
Number of nodes: 18631
Number of edges: 4102607
Average degree: 440.4065


loading cancer gene list

loading pathway id

In [5]:
A = nx.adjacency_matrix(G)

In [6]:
matrix = nx.to_numpy_array(G)
print(matrix)
'''
mat = nx.to_numpy_matrix(G)
print(mat)'''

[[0. 1. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 1. 0.]]


'\nmat = nx.to_numpy_matrix(G)\nprint(mat)'

In [7]:
matrix_dimension_reduction = np.linalg.svd(matrix)

In [8]:
print(matrix)

[[0. 1. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 1. 0.]]
