# Enviorment 

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
from scipy import stats
import seaborn as sns
from  matplotlib import pyplot as plt
import networkx as nx
plt.style.use('ggplot')
from tqdm import tqdm_notebook
import swifter
import qgrid
import numpy as np
import networkx as nx
import random
from scipy.sparse import spdiags
from functools import partial
import mygene
import sys

# Loading heterogeneous network

In [3]:
G = nx.read_edgelist("../data/heterogeneous_STRINGPhysical_KEGG.txt")

In [4]:
print(nx.info(G))

Name: 
Type: Graph
Number of nodes: 19273
Number of edges: 4345369
Average degree: 450.9281


In [6]:
A = nx.adjacency_matrix(G)

In [7]:
matrix = nx.to_numpy_array(G)
print(matrix)
'''
mat = nx.to_numpy_matrix(G)
print(mat)'''

[[0. 1. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 1. 0.]]


In [ ]:
matrix_dimension_reduction = np.linalg.svd(matrix)